move upgrade to function

diff --git a/bin/pushover b/bin/pushover
--- a/bin/pushover
+++ b/bin/pushover
@@ -11,47 +11,6 @@ EXPIRE="86400"
 ERROR=false
 VERSION="1.0.3"
 
-usage() {
-	echo "
-Usage:
-	pushover [options]
-Options:
-	--user 			Pushover user key. REQUIRED.
-	--token 		Pushover application API token. REQUIRED.
-	--title 		Notification title.
-	--message 		Notification message. REQUIRED.
-	--html 			Enabled HTML message. Set to 1 to enable. See: https://pushover.net/api#html.
-	--priority 		Message priority, see: https://pushover.net/api#priority. DEFAULT = $PRIORITY.
-	--retry 		How many seconds between retries. Only applies when --priority is set to 2 (emergency). DEFAULT = $RETRY.
-	--expire 		How many seconds until emergency notification retries will stop. Only applies when --priority is set to 2 (emergency). DEFAULT = $EXPIRE.
-	--configure 	Configure global Pushover user key and application API token.
-	--upgrade 		Upgrade to the latest version of Pushover CLI.
-	--version		Currently installed version of Pushover CLI.
-	--help 			Usage instructions.
-Example:
-	pushover \\
-	--user YOUR_USER_KEY \\
-	--token YOUR_APP_TOKEN \\
-	--title \"Test Notification\" \\
-	--message \"Here is the notification!\"
-	"
-}
-upgrade() {
-	DIR_TEMP=/opt/pushover-cli
-	git clone git@github.com:aaronfagan/pushover-cli.git $DIR_TEMP > /dev/null
-	if [ $? != 0 ];
-	then 
-		find $DIR_TEMP -type f -name "upgrade.sh" -exec chmod +x {} \; -exec bash {} \;
-		rm -rf $DIR_TEMP
-		exit 0
-	else
-		rm -rf $DIR_TEMP
-		echo -ne '\033[0;37m'
-		echo -ne "\nPushover CLI upgraded failed.\n\n"
-		echo -ne '\033[0m'
-		exit 1
-	fi
-}
 configure() {
 	echo -ne '\033[0;37m'
 	if [ -e $HOME/.pushover/config ]
@@ -77,6 +36,53 @@ EOF
 	chmod 600 $HOME/.pushover/config
 	echo -ne "\nPushover CLI configured successfully.\n\n"
 	echo -ne '\033[0m'
+}
+upgrade() {
+	DIR_TEMP=/opt/pushover-cli
+	git clone git@github.com:aaronfagan/pushover-cli.git $DIR_TEMP > /dev/null
+	if [ $? != 0 ];
+	then 
+		find $DIR_TEMP -type f -name "upgrade.sh" -exec chmod +x {} \; -exec bash {} \;
+		rm -rf $DIR_TEMP
+		exit 0
+	else
+		rm -rf $DIR_TEMP
+		echo -ne '\033[0;37m'
+		echo -ne "\nPushover CLI upgraded failed.\n\n"
+		echo -ne '\033[0m'
+		exit 1
+	fi
+}
+version() {
+	echo -ne "\033[0;37m
+\nPushover CLI - v$VERSION\n
+By Aaron Fagan (https://www.aaronfagan.ca/)\n\n
+\033[0m"
+}
+usage() {
+	echo "
+Usage:
+	pushover [options]
+Options:
+	--user 			Pushover user key. REQUIRED.
+	--token 		Pushover application API token. REQUIRED.
+	--title 		Notification title.
+	--message 		Notification message. REQUIRED.
+	--html 			Enabled HTML message. Set to 1 to enable. See: https://pushover.net/api#html.
+	--priority 		Message priority, see: https://pushover.net/api#priority. DEFAULT = $PRIORITY.
+	--retry 		How many seconds between retries. Only applies when --priority is set to 2 (emergency). DEFAULT = $RETRY.
+	--expire 		How many seconds until emergency notification retries will stop. Only applies when --priority is set to 2 (emergency). DEFAULT = $EXPIRE.
+	--configure 	Configure global Pushover user key and application API token.
+	--upgrade 		Upgrade to the latest version of Pushover CLI.
+	--version		Currently installed version of Pushover CLI.
+	--help 			Usage instructions.
+Example:
+	pushover \\
+	--user YOUR_USER_KEY \\
+	--token YOUR_APP_TOKEN \\
+	--title \"Test Notification\" \\
+	--message \"Here is the notification!\"
+	"
 }
 
 while [[ $# -gt 0 ]]
@@ -131,8 +137,7 @@ do
 			upgrade
 		;;
 		-v | --version)
-			echo -ne "\033[0;37m\nPushover CLI - v$VERSION\033[0m\n"
-			echo -ne "\033[0;37mBy Aaron Fagan (https://www.aaronfagan.ca/)\033[0m\n\n"
+			version
 			exit 0
 		;;
 		--help)
