feat: enable upgrade to specific version

diff --git a/bin/pushover b/bin/pushover
--- a/bin/pushover
+++ b/bin/pushover
@@ -46,14 +46,18 @@ EOF
 upgrade() {
 	DIR_TEMP=/tmp/pushover-cli
 	if [ -z "$UPGRADE" ]; then UPGRADE="master"; fi
+	echo -ne '\033[0;37m'
+	echo -ne "\nDownloading latest version..."
 	git clone --branch $UPGRADE --depth 1 $REPO $DIR_TEMP -q
-	if [ $? == 0 ]; then 
+	if [ $? == 0 ]; then
+		echo -ne "done!\n"
 		find $DIR_TEMP -type f -name "upgrade.sh" -exec chmod +x {} \; -exec bash {} $DIR_TEMP \;
 		rm -rf $DIR_TEMP
+		echo -ne '\033[0m'
 		exit 0
 	else
 		rm -rf $DIR_TEMP
-		echo -ne '\033[0;37m'
+		echo -ne "failed!\n"
 		echo -ne "\nPushover CLI upgrade failed.\n\n"
 		echo -ne '\033[0m'
 		exit 1
