fixed: exit status codes

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -9,7 +9,7 @@ PRIORITY="0"
 RETRY="60"
 EXPIRE="86400"
 ERROR=false
-VERSION="1.0.1"
+VERSION="1.0.2"
 
 usage() {
 	echo "
@@ -32,7 +32,7 @@ Example:
 	--title \"Test Notification\" \\
 	--message \"Here is the notification!\"
 	"
-	exit 1
+	exit $1
 }
 
 while [[ $# -gt 0 ]]
@@ -87,20 +87,20 @@ do
 			bash upgrade.sh $VERSION
 			cd - > /dev/null 2>&1
 			rm -rf $DIR_TEMP
-			exit 1
+			exit
 		;;
 		--help)
 			usage
 		;;
 		-v | --version)
 			echo -e "\033[0;37m\nPushover CLI v$VERSION.\n\033[0m"
-			exit 1
+			exit
 		;;
 		*) 
 			INVALID+=("$1")
 			shift
 			echo -e "\033[0;31m\nERROR:\033[0;37m Invalid arguement: $INVALID\033[0m"
-			usage
+			usage(1)
 		;;
 	esac
 done
@@ -111,7 +111,7 @@ then
 	if [ -z "$USER" ]; then echo -e "\033[0;31mERROR:\033[0;37m --user arguement is required.\033[0m"; fi
 	if [ -z "$TOKEN" ]; then echo -e "\033[0;31mERROR:\033[0;37m --token arguement is required.\033[0m"; fi
 	if [ -z "$MESSAGE" ]; then echo -e "\033[0;31mERROR:\033[0;37m --message arguement is required.\033[0m"; fi
-	usage
+	usage(1)
 else
 	printf '\033[0;37m'
 	printf "\n> Sending notification..."
@@ -125,6 +125,6 @@ else
 		-F "message=${MESSAGE}" \
 		https://api.pushover.net/1/messages.json \
 	| grep 'errors' > /dev/null 2>&1
-	if [ $? != 0 ]; then printf "success!\n\n"; else printf "failed!\n\n"; fi
+	if [ $? != 0 ]; then printf "success!\n\n"; else printf "failed!\n\n"; exit 1; fi
 	printf '\033[0m'
 fi
