fixed: exit status codes

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -32,7 +32,6 @@ Example:
 	--title \"Test Notification\" \\
 	--message \"Here is the notification!\"
 	"
-	exit $1
 }
 
 while [[ $# -gt 0 ]]
@@ -87,20 +86,21 @@ do
 			bash upgrade.sh $VERSION
 			cd - > /dev/null 2>&1
 			rm -rf $DIR_TEMP
-			exit
+			exit 0
 		;;
 		--help)
 			usage
 		;;
 		-v | --version)
 			echo -e "\033[0;37m\nPushover CLI v$VERSION.\n\033[0m"
-			exit
+			exit 0
 		;;
 		*) 
 			INVALID+=("$1")
 			shift
 			echo -e "\033[0;31m\nERROR:\033[0;37m Invalid arguement: $INVALID\033[0m"
 			usage
+			exit 1
 		;;
 	esac
 done
@@ -126,6 +126,6 @@ else
 		-F "message=${MESSAGE}" \
 		https://api.pushover.net/1/messages.json \
 	| grep 'errors' > /dev/null 2>&1
-	if [ $? != 0 ]; then printf "success!\n\n"; else printf "failed!\n\n"; exit 1; fi
+	if [ $? != 0 ]; then printf "success!\n\n"; exit 0; else printf "failed!\n\n"; exit 1; fi
 	printf '\033[0m'
 fi
