add fail to send

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -106,7 +106,8 @@ else
 	-F "retry=${RETRY}" \
 	-F "expire=${EXPIRE}" \
 	-F "message=${MESSAGE}" \
-	https://api.pushover.net/1/messages.json > /dev/null 2>&1
-	[[ $? -eq 0 ]] && printf "failed!\n" || printf "done!\n"
+	https://api.pushover.net/1/messages.json \
+	| grep 'errors' > /dev/null 2>&1
+	if [ $? != 0 ]; then printf "done!\n"; else printf "failed!\n"; fi
 	printf '\033[0m'
 fi
